// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Platform

typedef GPB_ENUM(Platform) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Platform_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** /客户端平台定义 */
  Platform_Iphone = 0,

  /** /iOS手机 */
  Platform_Ipad = 1,

  /** /iPad平板 */
  Platform_Android = 2,
};

GPBEnumDescriptor *Platform_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Platform_IsValidValue(int32_t value);

#pragma mark - Enum ClientProtocolId

typedef GPB_ENUM(ClientProtocolId) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ClientProtocolId_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** /客户端协议号 */
  ClientProtocolId_Default = 0,

  /** /登陆协议 */
  ClientProtocolId_Login = 257,
};

GPBEnumDescriptor *ClientProtocolId_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ClientProtocolId_IsValidValue(int32_t value);

#pragma mark - ClientRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ClientRoot : GPBRootObject
@end

#pragma mark - HeadInfo

typedef GPB_ENUM(HeadInfo_FieldNumber) {
  HeadInfo_FieldNumber_Seq = 1,
  HeadInfo_FieldNumber_Cmd = 2,
};

@interface HeadInfo : GPBMessage

/** //客户端协议的包头 */
@property(nonatomic, readwrite) uint32_t seq;

@property(nonatomic, readwrite) uint32_t cmd;

@end

#pragma mark - Login

typedef GPB_ENUM(Login_FieldNumber) {
  Login_FieldNumber_Uid = 1,
  Login_FieldNumber_ProtoVersion = 2,
  Login_FieldNumber_ForceUpdateVersion = 3,
  Login_FieldNumber_Platform = 4,
  Login_FieldNumber_ClientId = 5,
  Login_FieldNumber_LoginToken = 6,
  Login_FieldNumber_ClientVersion = 7,
};

@interface Login : GPBMessage

/** /主协议号 0x0101 */
@property(nonatomic, readwrite) uint32_t uid;

/** /协议版本号 */
@property(nonatomic, readwrite) uint32_t protoVersion;

/** /强更版本号 */
@property(nonatomic, readwrite) uint32_t forceUpdateVersion;

/** /平台号 */
@property(nonatomic, readwrite) Platform platform;

/** /设备唯一码 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *clientId;

/** //登陆token */
@property(nonatomic, readwrite, copy, null_resettable) NSData *loginToken;

/** //客户端版本号 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *clientVersion;

@end

/**
 * Fetches the raw value of a @c Login's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Login_Platform_RawValue(Login *message);
/**
 * Sets the raw value of an @c Login's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLogin_Platform_RawValue(Login *message, int32_t value);

#pragma mark - LoginRsp

typedef GPB_ENUM(LoginRsp_FieldNumber) {
  LoginRsp_FieldNumber_Uid = 1,
};

@interface LoginRsp : GPBMessage

/** /登陆成功回包  0x0102 */
@property(nonatomic, readwrite) uint32_t uid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
